a2lix_demo_translation_a2lix:
    resource: "@A2lixDemoTranslationA2lixBundle/Resources/config/routing.yml"
    prefix: /a2lix

a2lix_demo_translation_knp:
    resource: "@A2lixDemoTranslationKnpBundle/Resources/config/routing.yml"
    prefix: /knp

# Redirects
home_redir:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: a2lix_home
        permanent: true # this for 301
