a2lix_demo_translation:
    resource: "@A2lixDemoTranslationBundle/Resources/config/routing.yml"
    prefix: /translation

# Redirects
translation_home_redir:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: translation_home
        permanent: true # this for 301
