A2lixDemoTranslationBundle_BackendCustom:
    resource: "@A2lixDemoTranslationBundle/Controller/BackendCustom/"
    type:     annotation
    prefix:   /{_locale}/backend

A2lixDemoTranslationBundle_Frontend:
    resource: "@A2lixDemoTranslationBundle/Controller/Frontend/"
    type:     annotation
    prefix:   /
