controllers:
    resource: ../../src/Controller
    type:     annotation

controllers_backend_custom:
    resource: ../../src/Controller/BackendCustom
    type:     annotation
    prefix:   /{_locale}/backend
