services:
    a2lix_demo_translation.admin.knp.product:
        class: A2lix\DemoTranslationKnpBundle\Admin\ProductAdmin
        arguments: [~, A2lix\DemoTranslationKnpBundle\Entity\Product, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Knp Product}

    a2lix_demo_translation.admin.knp.category:
        class: A2lix\DemoTranslationKnpBundle\Admin\CategoryAdmin
        arguments: [~, A2lix\DemoTranslationKnpBundle\Entity\Category, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Knp Category}

