A2lixDemoTranslationA2lixBundle_BackendCustom:
    resource: "@A2lixDemoTranslationA2lixBundle/Controller/BackendCustom/"
    type:     annotation
    prefix:   /{_locale}/backend

#A2lixDemoTranslationA2lixBundle_BackendSonata:
#    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
#    prefix: /admin
#
#_A2lixDemoTranslationA2lixBundle_BackendSonata:
#    resource: .
#    type: sonata_admin
#    prefix: /admin

A2lixDemoTranslationA2lixBundle_Frontend:
    resource: "@A2lixDemoTranslationA2lixBundle/Controller/Frontend/"
    type:     annotation
    prefix:   /