services:
    a2lix_demo_translation.admin.product:
        class: A2lix\DemoTranslationA2lixBundle\Admin\ProductAdmin
        arguments: [~, A2lix\DemoTranslationA2lixBundle\Entity\Product, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: A2lix Product}

    a2lix_demo_translation.admin.category:
        class: A2lix\DemoTranslationA2lixBundle\Admin\CategoryAdmin
        arguments: [~, A2lix\DemoTranslationA2lixBundle\Entity\Category, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: A2lix Category}
